### ISSUE TITLE
Implement a `run` command with container support

### ISSUE THREAD

**Issue by mih** [datalad/datalad-container#10]
This would sit on top of datalad's `run` and utilize its `--input` management support that is coming in https://github.com/datalad/datalad/pull/2464

This should turn into a PR that gets developed against this datalad PR.

**Comment by yarikoptic** [comment]
How do you see to utilize inputs? For mount bind?

**Comment by mih** [comment]
That could be done. Q is if it is needed. Let's talk in a few min.
