### ISSUE TITLE
containers-run should install/get the subdataset if a container from subdataset was requested

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-container#122]
e.g.
```
(git-annex)lena:~/proj/repronim/demo-study[master]git-annex
$> datalad containers-run -n containers/bids-fmriprep -- --help
[ERROR  ] No known containers. Use containers-add [find_container.py:find_container:71] (ValueError) 

$> datalad --version
datalad 0.13.0.dev302
```

`containers/` subdataset is uninstalled.  `containers-run` has the information that container comes from a subdataset, so it should install it first. (may be actual isssue is deeper inside the datalad as for treatment of extra inputs).

after manually installing it -- containers-run works

<details><summary>DataLad 0.13.0.dev302 WTF (configuration, datalad, dataset, dependencies, environment, extensions, git-annex, location, metadata_extractors, python, system)</summary>

# WTF
## datalad 
  - full_version: 0.13.0.dev302-g8ed48
  - version: 0.13.0.dev302
## dataset 
  - id: c7947854-c845-11ea-8e05-87261519fb0a
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /home/yoh/proj/repronim/demo-study
  - repo: AnnexRepo
## dependencies 
  - annexremote: 1.4.3
  - appdirs: 1.4.3
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20200617+git192-g5849bd634-1~ndall+1
  - cmd:bundled-git: 2.24.0
  - cmd:git: 2.24.0
  - cmd:system-git: 2.27.0
  - cmd:system-ssh: 8.1p1
  - exifread: 2.1.2
  - git: 3.1.0
  - gitdb: 4.0.2
  - humanize: 2.3.0
  - iso8601: 0.1.12
  - keyring: 18.0.1
  - keyrings.alt: 3.4.0
  - msgpack: 0.6.2
  - mutagen: 1.40.0
  - requests: 2.23.0
  - tqdm: 4.43.0
  - wrapt: 1.11.2
## environment 
  - GIT_PAGER: less --no-init --quit-if-one-screen
  - LANG: en_US.UTF-8
  - PATH: /home/yoh/proj/datalad/datalad-container/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin
## extensions 
  - container: 
    - description: Containerized environments
    - entrypoints: 
      - datalad_container.containers_add.ContainersAdd: 
        - class: ContainersAdd
        - load_error: None
        - module: datalad_container.containers_add
        - names: 
          - containers-add
          - containers_add
      - datalad_container.containers_list.ContainersList: 
        - class: ContainersList
        - load_error: None
        - module: datalad_container.containers_list
        - names: 
          - containers-list
          - containers_list
      - datalad_container.containers_remove.ContainersRemove: 
        - class: ContainersRemove
        - load_error: None
        - module: datalad_container.containers_remove
        - names: 
          - containers-remove
          - containers_remove
      - datalad_container.containers_run.ContainersRun: 
        - class: ContainersRun
        - load_error: None
        - module: datalad_container.containers_run
        - names: 
          - containers-run
          - containers_run
    - load_error: None
    - module: datalad_container
    - version: 1.0.1
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.0.0
    - ghc-8.4.4
    - http-client-0.5.13.1
    - persistent-sqlite-2.8.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - local repository version: 8
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20200617+git192-g5849bd634-1~ndall+1
## location 
  - path: /home/yoh/proj/repronim/demo-study
  - type: dataset
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py) [Image.py:<module>:69]
    - module: datalad.metadata.extractors.image
  - xmp: 
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.7.3rc1
## system 
  - distribution: debian/bullseye/sid
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 290
  - name: Linux
  - release: 5.6.0-1-amd64
  - type: posix
  - version: #1 SMP Debian 5.6.7-1 (2020-04-29)
</details>

**Comment by yarikoptic** [comment]
I keep running into this. No immediate urgency (since workaround is easy) but would be nice to have it addressed

**Comment by kyleam** [comment]
Could you provide a reproducer?  The download is triggered on my end.

<details>
<summary>script</summary>

```sh
#!/bin/sh

cd "$(mktemp -d "${TMPDIR:-/tmp}"/dl-XXXXXXX)"

datalad create
datalad install -d . git@github.com:ReproNim/containers.git
datalad containers-run -n containers/bids-fmriprep -- --help
```

```
[...]
action summary:
  add (ok: 2)
  install (ok: 1)
  save (ok: 1)
[INFO   ] Making sure inputs are available (this may take some time) 
images/bids/bids-fmriprep--20.1.1.sing:   2%|▎                      | 78.4M/4.87G [00:06<11:11, 7.13MB/s]^C[WARNING] Still have 1 active progress bars when stopping 
ERROR:                                                                                                   
Interrupted by user while doing magic: KeyboardInterrupt() [cmd.py:_process_one_line:777]
```

</details>

**Comment by yarikoptic** [comment]
Thanks for the script -- just add `uninstall` call after you `install` containers subdataset.

<details>
<summary>like in here</summary> 

```shell
#!/bin/sh

cd "$(mktemp -d "${TMPDIR:-/tmp}"/dl-XXXXXXX)"

datalad create
datalad install -d . git@github.com:ReproNim/containers.git
datalad uninstall containers
datalad containers-run -n containers/bids-fmriprep -- --help
```
</details>

<details>
<summary>output</summary> 

```shell
$> bash containers-reproducer.sh                            
[INFO   ] Creating a new annex repo at /home/yoh/.tmp/dl-iBRhj9C 
[INFO   ] Scanning for unlocked files (this may take some time) 
create(ok): /home/yoh/.tmp/dl-iBRhj9C (dataset)
[INFO   ] Scanning for unlocked files (this may take some time)                                                  
[INFO   ] Unable to parse git config from origin                                                                 
[INFO   ] Remote origin does not have git-annex installed; setting annex-ignore
|   This could be a problem with the git-annex installation on the remote. Please make sure that git-annex-shell is available in PATH when you ssh into the remote. Once you have fixed the git-annex installation, run: git annex enableremote origin 
install(ok): /home/yoh/.tmp/dl-iBRhj9C/containers (dataset)
add(ok): /home/yoh/.tmp/dl-iBRhj9C/containers (file)
add(ok): /home/yoh/.tmp/dl-iBRhj9C/.gitmodules (file)
save(ok): /home/yoh/.tmp/dl-iBRhj9C (dataset)
action summary:
  add (ok: 2)
  install (ok: 1)
  save (ok: 1)
uninstall(ok): /home/yoh/.tmp/dl-iBRhj9C/containers (dataset)
action summary:
  drop (notneeded: 1)
  uninstall (ok: 1)
[ERROR  ] No known containers. Use containers-add [find_container.py:find_container:71] (ValueError) 
bash containers-reproducer.sh  5.93s user 2.39s system 90% cpu 9.184 total

```
</details>

**Comment by kyleam** [comment]
> just add `uninstall` call after you `install` containers subdataset.

Thanks.

This depends on `containers-list`, which not surprisingly only considers installed datasets.

https://github.com/datalad/datalad-container/blob/634ac22d0fb42d6b3d75655d14ff3e3f2d61ed94/datalad_container/containers_list.py#L53-L65

So, to add this feature, `containers-run`  (perhaps via `find_container`) needs to be reworked to recursively install the datasets if needed.

**Comment by kyleam** [comment]
> yeap, aligns with "so it should install it first." in the initial issue description

Yes, and notably doesn't align with what came immediately after: "(may be actual isssue is deeper inside the datalad as for treatment of extra inputs)".
