### ISSUE TITLE
support for Amazon ECR (docker containers registry)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-container#124]
A use case of @nicholsn where they heavily rely on AWS, and use ECR for their containers.  I wonder if it would be just enough to do all the `docker login` dance first and then just adding `ecr://` (as opposed to `dhub://`) to fetch the layers (since docker works with it - I expect ECR exposing itself through some standard open containers or whatnot interface).

More info https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/

Example of the target image "name" after `docker login` is `16XXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/maze-code/whatever-count:latest`

**Comment by nicholsn** [comment]
ECR is docker registry compatible, once logged into ecr this will just work using the `dhub://` prefix

**Comment by yarikoptic** [comment]
so if I got it right, there is nothing for us to do. @nicholsn please confirm or disconfirm (and I would reopen) ;)

**Comment by adswa** [comment]
\*makes mental note to add this to the handbook\*
