### ISSUE TITLE
Windows Docs/FOI?: Sharing the C drive is a requirement

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-container#139]
Maybe this is something that Windows Docker users know, but I'm sharing it as an FOI or as something to go as a note into the docs: Users need to adjust the Docker settings to share the C:// drive in order to be able to mount directories with ``-v``.
![dockercdrive](https://user-images.githubusercontent.com/29738718/98694050-4c1a4a00-2371-11eb-80ee-da5da1a145d0.png)

Feel free to close this at any point.

**Comment by yarikoptic** [comment]
yikes, thanks for the info!
