### ISSUE TITLE
`run` attempts command even when container download failed

### ISSUE THREAD

**Issue by mih** [datalad/datalad-container#147]
Demo log

```
[DEBUG] Launching process ['git', 'annex', 'get', '--json', '--json-error-messages', '--json-progress', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3', '--', '.datalad/environments/cat/image'] 
[DEBUG] Process 31133 started 
[DEBUG] Waiting for process 31133 to complete 
[DEBUG] Process 31133 exited with return code 1 
[DEBUG] received JSON result from annex: {'command': 'get', 'wanted': [{'here': False, 'uuid': 'c02d1dd5-ea40-4f55-a695-ab75dd609e34', 'description': 'mih@juseless:/data/project/ukb_vbm/pipeline_ds/cat-container'}, {'here': False, 'uuid': 'f6f7531f-3b15-4ac9-a6c1-c3ff213078d2', 'description': '[inm7-storage]'}], 'note': 'from inm7-storage...\nfrom inm7-storage...\nfrom inm7-storage...\nUnable to access these remotes: inm7-storage\nTry making some of these repositories available:\n\tc02d1dd5-ea40-4f55-a695-ab75dd609e34 -- mih@juseless:/data/project/ukb_vbm/pipeline_ds/cat-container\n \tf6f7531f-3b15-4ac9-a6c1-c3ff213078d2 -- [inm7-storage]\n\n(Note that these git remotes have annex-ignore set: origin)', 'skipped': [], 'success': False, 'key': 'MD5E-s2289532959--351691ea15179f0a8acfbf59adb31088', 'error-messages': [], 'file': '.datalad/environments/cat/image'} 
[ERROR] from inm7-storage...; from inm7-storage...; from inm7-storage...; Unable to access these remotes: inm7-storage; Try making some of these repositories available:;       c02d1dd5-ea40-4f55-a695-ab75dd609e34 -- mih@juseless:/data/project/ukb_vbm/pipeline_ds/cat-container;   f6f7531f-3b15-4ac9-a6c1-c3ff213078d2 -- [inm7-storage]; ; (Note that these git remotes have annex-ignore set: origin) [get(/var/lib/condor/execute/dir_27945/ds/code/pipeline/.datalad/environments/cat/image)] 
[DEBUG] chdir '/var/lib/condor/execute/dir_27945/ds' -> '/var/lib/condor/execute/dir_27945/ds' (coming back) 
[INFO] == Command start (output follows) ===== 
[DEBUG] Async run singularity exec -B /var/lib/condor/execute/dir_27945/ds --cleanenv code/pipeline/.datalad/environments/cat/image sh -e -u -x -c '
    echo 5588468.395894 > 5588468.395894.funky.funky' 
[DEBUG] Launching process singularity exec -B /var/lib/condor/execute/dir_27945/ds --cleanenv code/pipeline/.datalad/environments/cat/image sh -e -u -x -c '
    echo 5588468.395894 > 5588468.395894.funky.funky' 
[DEBUG] Process 3773 started 
[DEBUG] Waiting for process 3773 to complete 
ERROR  : Image path code/pipeline/.datalad/environments/cat/image doesn't exist: No such file or directory
ABORT  : Retval = 255
[DEBUG] Process 3773 exited with return code 255 
[INFO] == Command exit (modification check follows) ===== 
[INFO] The command had a non-zero exit code. If this is expected, you can save the changes with 'datalad save -d . -r -F .git/COMMIT_EDITMSG' 
CommandError: 'singularity exec -B /var/lib/condor/execute/dir_27945/ds --cleanenv code/pipeline/.datalad/environments/cat/image sh -e -u -x -c '
```

If the container cannot be obtained any further action is pointless.

**Comment by bpoldrack** [comment]
This would prob. need to be addressed in datalad core. `containers-run` doesn't explicitly get the container but rather specifies it as `extra_inputs` for `run`. So, it's `run` that needs to fail if it can't fulfill the inputs. Don't think making `containers-run` retrieve it before hand is the way to go.

**Comment by kyleam** [comment]
> it's `run` that needs to fail if it can't fulfill the inputs

`run` yields `action=get,status=error` results, so `containers-run` _could_ act on it.  Conceptually, though, I agree that `run` is the better spot to handle this and that it should bail before running the command if `get` fails.  However, without looking too closely, I think there are special cases that would need to be checked/thought through (e.g., non-matching globs), and I doubt it will end up being as simple as adding a `return` after a failed `get`.

It's also worth noting that the containers-run caller could fail earlier here with `--on-failure=stop`:

```sh
cd "$(mktemp -d "${TMPDIR:-/tmp}"/dl-XXXXXXX)"

datalad create
datalad containers-add --url docker://busybox:latest bb
git annex drop --force .
datalad -f json_pp --on-failure=stop containers-run true
```

```
[...]
[INFO] Making sure inputs are available (this may take some time) 
[ERROR] not available [get(/tmp/dl-dOrsUEv/.datalad/environments/bb/image)] 
{
  "action": "get",
  "annexkey": "MD5E-s741407--c9aed71287f2f96758ac0c4fa6892369",
  "path": "/tmp/dl-dOrsUEv/.datalad/environments/bb/image",
  "refds": "/tmp/dl-dOrsUEv",
  "status": "error",
  "type": "file"
}
```

**Comment by bpoldrack** [comment]
> I think there are special cases that would need to be checked/thought through (e.g., non-matching globs), and I doubt it will end up being as simple as adding a return after a failed get.

Agree. I'm not sure any failed `get` should lead to abortion.

Arguably, it's worth doing both: Generally better account for this within `run` but also explicitly abort `containers-run` if we get an error result w/ `action='get'` and `path=<the container>`. That's because no matter how serious other get errors may or may not be, not having the container we are supposed to run something in definitely is fatal.

**Comment by yarikoptic** [comment]
> If the container cannot be obtained any further action is pointless

it would indeed guaranteed to result in a failed run, but might be not that pointless -- may be I fired it up and went for a break and meanwhile it would have fetched all the data, so whenever I come back I could just fix the name of container and "re-run" without now waiting for a lengthy "get the data".  The point is that there could still be some value.  

And container is likely not that much special in this respect - if input data fails to `get` later, we should not continue with execution.

Having said that, in principle, `datalad-container` could explicitly `get` container first before passing it as `extra_inputs` into `run`.

**Comment by bpoldrack** [comment]
> whenever I come back I could just fix the name of container and "re-run" without now waiting for a lengthy "get the data".

Could also be the other way around. May be some `get` is correctly failing (no permission or something) because I used the wrong glob and now we continue to download a ton of data that I don't need at all.
Guessing that something might be useful despite the fact the command can't fulfill what it was asked to do always leads to very oppinionated outcomes IMO.

> And container is likely not that much special in this respect - if input data fails to get later, we should not continue with execution.

Not sure. May be I specify just `data/*` to have a generic record that I can re-run on other versions and it's perfectly fine to get what we can but not necessarily everything. And it might be difficult to be more specific and still capture all cases, since the actual program I'm running is inspecting that folder to find out what to do.
Point is: Failure to get everything isn't bound to lead to a failure of execution. Depends on precision of the specified input wrt to what's actually required. The container, however, definitely is required.

**Comment by yarikoptic** [comment]
I guess it was fixed in https://github.com/datalad/datalad/commit/91d63ef455f8a7457224e57215b35e847cc5ccf9 circa datalad 0.14.x
