### ISSUE TITLE
Environments are added to git by default

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad-container#15]
By default, `datalad create` currently creates the following .gitattributes file:

```
% cat .datalad/.gitattributes
# Text files (according to file --mime-type) are added directly to git.
# See http://git-annex.branchable.com/tips/largefiles/ for more info.
** annex.largefiles=nothing
metadata/objects/** annex.largefiles=(largerthan=20kb)
```

By these rules, images in .datalad/environments will be added to git rather than git-annex.  I think datalad-container should add something like `environments/** annex.largefiles=anything` to .datalad/.gitattributes to prevent this.

**Comment by mih** [comment]
True. Thanks!

**Comment by mih** [comment]
@kyleam @yarikoptic Thinking about it. Maybe it would be better if datalad's `create()` would be a less bold and only fore those bits into Git that we actuall know about (`.datalad/config` pretty much), instead of everything?

**Comment by kyleam** [comment]
Right, that seems like a better idea.

**Comment by mih** [comment]
Should be gone now. Tests will come when initial draft of commands is complete

**Comment by yarikoptic** [comment]
I think `.datalad/environments` would just need its own .gitattributes.  E.g. most likely there we would like to allow all text files into git (unlikely any private information would leak, unlike in metadata).  This will be handy for docker extracted images so we get tarballs into annex (if lucky referencing them from hub etc) and metadata on them in git "for posterity"

**Comment by mih** [comment]
Yes. Note, however, that this folder is merely the default location, and there is no requirement to have all environments located underneath it.
