### ISSUE TITLE
Document usage with docker

### ISSUE THREAD

**Issue by arokem** [datalad/datalad-container#159]
Based on the documentation [here](http://docs.datalad.org/projects/container/en/latest/generated/man/datalad-containers-add.html#u-url-url-url), I would've assumed that the command: `datalad containers-add bar -u docker://foo/bar:0.1` would try to use docker, but in fact, it tried to use Singularity (which failed, as I am running on a Mac laptop). This led me to think that maybe datalad-container doesn't work with Docker at all , which I am now convinced is not true (but is not apparent just from reading the documentation...): Running `datalad containers-add bar -u dhub://foo/bar:0.1` does seem to use docker.

At any rate, would be nice to make this a bit clearer. In particular, under what circumstances is docker used and when is singularity used.

**Comment by mih** [comment]
Thank you for the report. I posted #164 to clarify this in the documentation (a bit better).
