### ISSUE TITLE
Argument to "docker pull" does not work as "dhub://" URL

### ISSUE THREAD

**Issue by arokem** [datalad/datalad-container#160]
This is a docker call that works: 

`docker pull ghcr.io/nrdg/afqsi:0af517b896dd162d84e7d833539391c213261b61`

But `datalad containers-add dhub://ghcr.io/nrdg/afqsi:0af517b896dd162d84e7d833539391c213261b61` raises:

```
[ERROR  ] ValueError(Container names can only contain alphanumeric characters and '-', got: 'dhub://ghcr.io/nrdg/afqsi:0af517b896dd162d84e7d833539391c213261b61') (ValueError) 
```

**Comment by mih** [comment]
Hi @arokem!

Sorry for the long silence. I believe the command just wants to be called differently. The positional argument is the container name, and the URL must be an option. One would have to think about the rational behind this design....

In any case, the following seems to work:

```sh
% datalad containers-add -u dhub://ghcr.io/nrdg/afqsi:0af517b896dd162d84e7d833539391c213261b61 mycontainer
0af517b896dd162d84e7d833539391c213261b61: Pulling from nrdg/afqsi
4f53fa4d2cf0: Pull complete 
...
```

(did not wait for completion, it want to pull a lot of layers, and big ones...)
