### ISSUE TITLE
Update Travis config to use new codecov uploader

### ISSUE THREAD

**Issue by jwodder** [datalad/datalad-container#162]
On June 9, codecov released a new version of their coverage uploader program to replace the old bash uploader, which will stop working on February 1 and is currently experiencing scheduled brownouts; see [this blog post](https://about.codecov.io/blog/introducing-codecovs-new-uploader/) for more information.  This repository's Travis config must be updated to install the new codecov uploader; see the linked blog post for instructions.

**Comment by adswa** [comment]
I'm closing this issue as resolved, because Travis has been removed from this repo in #210, and the appveyor configuration was adjusted (I believe) in https://github.com/datalad/datalad-container/commit/8e18d608579c59f3b07bcdbec5b27842c93b6c65
