### ISSUE TITLE
RFE: Add environment variables option

### ISSUE THREAD

**Issue by asmacdo** [datalad/datalad-container#194]
IMO, containers should usually be configured via environment variables, so it seems like
`datalad containers-run` should accept `--env` and `--env-file` and pass along to singularity.

Alternatively, we could also add a flag `--singularity-vars "env-file=/home/here"` or similar.

**Comment by yarikoptic** [comment]
yeah, might be useful to allow for custom env configuration for a container.  In principle that can already be possible for people by tuning their fork of this dataset and changing invocations in .datalad/config accordingly.  Before bothering to improve upon that we better gain specific use cases to address.

**Comment by asmacdo** [comment]
My only use case was experimenting. closing for now, if anyone needs this please reopen and post your use case!
