### ISSUE TITLE
`containers-add` produces platform-specific configuration

### ISSUE THREAD

**Issue by mih** [datalad/datalad-container#224]
```ini
[datalad "containers.debian"]
	image = .datalad\\environments\\debian\\image
	cmdexec = python.exe -m datalad_container.adapters.docker run {img} {cmd}
```

The python executable is not portable and the path separators also not.

**Comment by mih** [comment]
Fixing the path separator in a yes-we-remain-compatible-with-1893 will be complex. Theoretically, directory names with backslashes are legal. So we cannot simply force convert them.

So to make things smooth, we would need to employ heuristics/guesswork. This means adding code to do that and maintain it forever. The target audience is windows users that use containers-run on windows and never give the resulting datasets to other platforms (for those things have never worked).

For those, and in some cases, the path could be checked and auto-converted against the annex placeholder. However, that is only possible, when the image is hosted in the same dataset -- further complicating the logic and still not being comprehensive.

That being said, I am comfortable with an entry in the changelog that says "Windows: manual fixing needed".

**Comment by mih** [comment]
This issue is further complicated by the fact that all this code is pre-`pathlib`.

**Comment by yarikoptic** [comment]
since not said explicitly I think - I think we should store only POSIX paths there, so fix code and add mapping to OS specific path (pathlib or not). Adding heuristic to fix paths either starting with `r".datalad\\"` or containing `r"\\.datalad\\"` in the path would also cover most of the use cases.

**Comment by mih** [comment]
I arrived at the same conclusion and have a partial patch for that. Rollout is difficult, will file separate issue
