### ISSUE TITLE
Bump minimum datalad version?

### ISSUE THREAD

**Issue by mih** [datalad/datalad-container#234]
Quite a few deprecation warnings that stem from usage of outdated datalad pieces.

- config manager `where=` and not `scope=` is used
- `remove(save=)` is used
- `remove(check=)` is used
- `uninstall()` is used (rather than `drop`)

Presently, the minimum datalad version is v0.18. Are there reasons to not bump that to v0.19?

**Comment by yarikoptic** [comment]
Just for clarity - it is not just about bumping it up, but changing the code to use those newer interfaces. Indeed 0.19 was out long enough, worth changing

**Comment by mih** [comment]
Thanks. I will consider a v0.19 a possibility and adjust code that I touch accordingly .
