### ISSUE TITLE
Adding image to inputs may surprise users that use "{inputs}" placeholder

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad-container#38]
Taking containers-run as a drop-in replacement for run, a user wouldn't expect to see the image at the end of the input list.

```bash
%> datalad containers-run "echo foo >foo"
%> datalad containers-run --input=foo "echo {inputs} | sed 's/ /\n/g' >input-list"
%> cat input-list
foo
.datalad/environments/bbox/image
```

We could add yet another argument (something like `inputs_extra`) to `run.run_command` and have containers-run use that directly.  I don't think that's pretty, but I can't think of anything else at the moment.

**Comment by yarikoptic** [comment]
I think it just once again outlines unclear semantic of `--input` which is really `--files-to-get` ATM, and not necessarily inputs to the command.  Container is not really an input of any kind -- it is just something more to `--get`.  What about adding to `run` explicit `--get` argument?  Both `--input` and `--get` listed files will be fetched before execution, but obviously `--get` listed files will not be part of `{inputs}`

**Comment by kyleam** [comment]
> I think it just once again outlines unclear semantic of --input

AFAIK your "once again" refers to private comments you've made to me.  Or are there other open issues/discussions that you're referring to here?

> which is really --files-to-get ATM, and not necessarily inputs to the command

In all the scenarios I can think of, "files to get" is a subset of inputs (because some inputs might not be annexed files).

> Container is not really an input of any kind -- it is just something more to --get

I view the container as an input to the *run*, in the same way a script is; it's just surprising for the caller because `containers-run` is handling it for the user.  Even if you restricted the concept of "inputs" to the inputs of the *command*, I don't find things that much clearer: `singularity exec INPUTS ...`, where INPUTS includes the image file.  I realize it's just a matter of where you choose to draw the line, but I do disagree with the "not really an input of any kind".

ATM --input is only useful to specify inputs for getting.  The main situation where I can see this changing is if we support exporting to various workflows and want to fill in their inputs field.  In that case, you'd want inputs to include the annex files as well.

> What about adding to run explicit --get argument?

Perhaps.  If we are going to add another option, I would prefer that we come up with a clear, documented description of what we mean by "inputs".  And presumably for symmetry you would want an --unlock (--remove?) counterpart for --output?

An advantage to my proposed solution is that it is much less user-facing, so we're not committing to much.

**Comment by mih** [comment]
Regarding the semantics of `inputs` I agree with @kyleam. Whatever name we would use it wouldn't make the original issue go away, as it is about silently adding to the list. And I can attest that the problem is real, it surprise me today.

Initially I thought to agree that `--inputs-extra` is ugly, but after the third round I don't agree anymore. It is pretty much exactly what we need. We need an options that is just like `--inputs` (or whatever name), but does show up when expanding the `{inputs}` placeholder.

If we make this change, it would probably be useful to add the second placeholder `{inputs_extra}` right away.

**Comment by yarikoptic** [comment]
Let me add an explicit +1 on this "right away" action to be taken!  This issue surprised me today again, and I only had a vague recollection of this discussion before.
