### ISSUE TITLE
singularity home directory

### ISSUE THREAD

**Issue by satra** [datalad/datalad-container#43]
on some systems $PWD is not automatically bind mounted. see this: https://github.com/singularityware/singularity/issues/150

i had to do this to work on our local system (centos)
```
$ singularity exec -C -H `pwd` .datalad/environments/heudiconv/image ls -a
.  ..  .datalad  .git  .gitattributes  .gitmodules  inputs
```

it would be nice to be able to adjust the execution of `datalad containers-run`
also is `datalad containers-run` equivalent to `datalad run singularity exec ...` from a metadata capture standpoint?

**Comment by satra** [comment]
testing with:

```
datalad run singularity exec -C -H `pwd` .datalad/environments/heudiconv/image heudiconv -f reproin -s 02 -c dcm2niix -b -l '' --minmeta -a . -o /tmp/heudiconv.sub-02 --files inputs/rawdata/dicoms
```

**Comment by satra** [comment]
just updating as i go along. then i ran out of `/tmp` space:

to succeed i had to do the following. 

```
    [DATALAD RUNCMD] singularity exec -c -B /tmp -H /om/scrat...
    
    === Do not change lines below ===
    {
     "chain": [],
     "cmd": "singularity exec -c -B /tmp -H /om/scratch/Fri/satra/training/test-exercises/bids .datalad/environments/heudiconv/image heudiconv -f reproin -s 02 -c dcm2niix -b -l '' --minmeta -a . -o /tmp/heudiconv.sub-02 --files inputs/rawdata/dicoms",
     "dsid": "54ff1f28-6c5e-11e8-a43a-3085a926759a",
     "exit": 0,
     "inputs": [],
     "outputs": [],
     "pwd": "."
    }
    ^^^ Do not change lines above ^^^
```

**Comment by mih** [comment]
Here is what I use on our cluster when adding/configuring the container:

```
datalad containers-add conversion \
    -u shub://mih/ohbm2018-training:heudiconv \
    --call-fmt 'singularity exec --bind {{pwd}} {img} {cmd}'
```

You can check `.datalad/config` for the configuration of `callfmt` in your dataset, and alter it accordingly.

**Comment by satra** [comment]
thanks! will check it out and see if this fixes the other issues.

**Comment by satra** [comment]
this works on my cluster now with:

`--call-fmt 'singularity exec -B /tmp --bind {{pwd}} -H {{pwd}} {img} {cmd}'`
