### ISSUE TITLE
add: local path for --url fails with git-annex 6.20180626

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad-container#47]
As expected, following git-annex 6.20180626, running containers-add with a local url and no additional configuration will fail:

```bash
%> datalad containers-add foo --url /tmp/foo.simg
Configuration does not allow accessing file:///tmp/foo.simg
Configuration does not allow accessing file:///tmp/foo.simg
git-annex: addurl: 1 failed
[ERROR  ] CommandError: command 'addurl'
| Error, annex reported failure for addurl (url='file:///tmp/foo.simg'): {'command': 'addurl', 'success': False, 'file': None} [containers_add(/tmp/dl/another/.datalad/environments/foo/image)]
containers_add(error): /tmp/dl/another/.datalad/environments/foo/image (file) [CommandError: command 'addurl'
Error, annex reported failure for addurl (url='file:///tmp/foo.simg'): {'command': 'addurl', 'success': False, 'file': None}]
containers_add(error): /tmp/dl/another/.datalad/environments/foo/image (file) [no image at /tmp/dl/another/.datalad/environments/foo/image]
action summary:
  containers_add (error: 2)
```

git-annex's output to stderr mentions that it's a configuration issue [*], but from that information alone I doubt many DataLad users would know what to do next.  So I think we should do something here.  The options I can think of:

  * Give a more specific error message (at the level of containers_add or annexrepo.add_url_to_file)

    We could tell the user the do something like `git config annex.security.allowed-url-schemes file`, but we shouldn't be recommending that setting to users.  It'd be nicer if we could recommend a one-time override with `datalad -c annex.security.allowed-url-schemes=file ...`, but that setting isn't propagated to the git-annex call (and would fail on subsequent `git annex get` calls).

  * Stop supporting local files as an argument to --url

  * Add locals files via direct copying rather than an `add_url_to_file` call

    I think the main downside would be that the local source is no longer recorded by git-annex and we can't run `git annex get` on the file.

[*] I'm not sure why it does so twice; I guess add_url_to_file makes two addurl calls at some point, but I haven't checked.

**Comment by yarikoptic** [comment]
when do we want to point to local (file:///) urls? (if we assume that they aren't network paths, just local)  such urls wouldn't be versioned etc, thus susceptible to "version rot" (I think I came up with the new term! ;))

**Comment by kyleam** [comment]
> when do we want to point to local (file:///) urls?

I can't answer for "we", but I've used a local path with --url a good amount because it's a convenient way to say "I have this singularity image.  Add it to the current dataset, naming it with the default .datalad/environments/NAME/image scheme".  I don't rely on it pointing to the local url, so the last option I list would be fine for my purposes.

Anyway, the point is that `containers-add --url` was designed to support local files, and with the latest git-annex the default behavior is to fail.

**Comment by yarikoptic** [comment]
well, since the fix in annex was primarily to prevent acting on some malicious urls added by someone to the repository, not really while user explicitly providing file:// url, I think it would be ok to pass `-c annex.security.allowed-url-schemes=file` for that addurl call.  But then, that stored file:/// url would keep triggering annex to fail whenever you try to `get` it.  I guess annex/datalad would just go to another possible source for the file if there is one available (another clone etc) without causing the whole get to fail, so we should be ok.

**Comment by mih** [comment]
I am with @yarikoptic on this one, and to follow @kyleam's suggestion to give a more useful error message that points to a workaround, with a statement of the implications.

**Comment by yarikoptic** [comment]
I am with @mih and @kyleam and @bpoldrack on this one ;-)

**Comment by bpoldrack** [comment]
I can't stand that level of harmony. :-D

I'm actually in favor of a different handling. The point of `addurl` is to register that URL as a possible source and otherwise provide a shortcut to "download and add". When I ran into this with `datalad-hirni`, I went with replacing `addurl` by copy the damn file and `annex-add` it. We could do that generally whenever we encounter a file-scheme URL (or at least in `containers-add` if not generally from within `AnnexRepo.addurl`-methods).

**Comment by bpoldrack** [comment]
Because this:
> But then, that stored file:/// url would keep triggering annex to fail whenever you try to get it. But then, > that stored file:/// url would keep triggering annex to fail whenever you try to get it. 

eliminates the registering part anyway, so all the wanted functionality of `addurl` we are left with, is copy and add, IMO.

**Comment by yarikoptic** [comment]
4th option is to add configuration with choices fail, copy, url and handle accordingly

**Comment by kyleam** [comment]
I've gone with the copy/add approach in #55.  In my view, this isn't something we need to complicate with a configuration option.  If a user has set `annex.security.allowed-url-schemes` and wants the URL to be recorded, they can always explicitly specify "file://".
