### ISSUE TITLE
petition: for the sanity of humanity rename to datalad-containers

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-container#48]
**OR** rename all commands to be single : `container-run`, `container-add`, `container-list`.
This way it would stay consistent between the name of the extension and added commands namespace.

IMHO the easiest to rename the whole module and also it would sounds a bit more kosher, and inline with `siblings`, `subdatasets` etc commands of `datalad`. With plural version, only the `containers-run` would be a bit awkward (since we run only one container right, or not?) but still imho ok
We could provide a compatibility version of `datalad-container` pkg  for pypi to ease upgrades.

**Comment by kyleam** [comment]
You're not allowed to thumbs up your own issue.  I'll have to restore the balance :-)

I also dislike the inconsistency.  In terms of which direction to go, I'm not sure.  `add`, `remove`, and `run` all work on a single container.  `list` is the only one that concerns multiple, though I suppose it could be argued that `add` and `remove` are about adding/removing a single container from the collection of containers.

**Comment by mih** [comment]
I am in favor of either way: which one shall we use? I cannot really recall any particular reason for this mess. It should be noted that we should have complete freedom of name selection to be able to independently choose:

- package name
- extension name
- individual command names

There is no need for artificial singular/plural consistency across these three categories (but it it would make sense to me to have the first two be the same).

**Comment by kyleam** [comment]
My vote is to change the commands to use `container-`.

**Comment by bpoldrack** [comment]
Well, I am actually more attracted by @yarikoptic's argument for usage of plural.

> inline with siblings, subdatasets etc commands of datalad. 

Plus: I'd argue that a command name `something-command` clearly references the extension's name in the first part and the actual command in the second. So, I don't find the plural confusing, if the extension's name is using the plural. And the extension itself obviously is about containers.

**Comment by kyleam** [comment]
> Plus: I'd argue that a command name something-command clearly references the extension's name in the first part and the actual command in the second. So, I don't find the plural confusing

Fair enough, though that same argument could be made for not finding `container-` confusing (mostly `container-list`, I think, since I can view all the other commands as being focused on a single container).

Using the plural is fine with me, just not my preference.

**Comment by yarikoptic** [comment]
I guess nobody cares enough to cause the mess with renaming to gain consistency
