### ISSUE TITLE
some action/progress indication while doing heavy download

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-container#49]
ATM `containers-add` is showing no sign of any actions to be done and just hangs there possibly for hours (depending on bandwidth) to only spit out at the end the end feedback
```shell
(datalad) [bids@rolando QA] > datalad containers-add reproin --url shub://ReproNim/reproin
save(ok): /inbox/BIDS/dbic/QA (dataset)
containers_add(ok): /inbox/BIDS/dbic/QA/.datalad/environments/reproin/image (file)
action summary:
  containers_add (ok: 1)
  save (ok: 1)
```
At least some clue to the user (`Running singularity pull ... which might take a while`) or may be even channeling output from the command (by may be not swallowing it) back to the screen here could be a better course of action

**Comment by kyleam** [comment]
> At least some clue to the user (Running singularity pull ... which might take a while)

FTR `annexrepo.add_url_to_file`, not `singulartiy pull`, is called underneath.  But, yes, I agree we should give more information, and the code hints at that too:

https://github.com/datalad/datalad-container/blob/a8526c93ed362445c8ab12dff396cd1ea50c54b1/datalad_container/containers_add.py#L191-L197

**Comment by yarikoptic** [comment]
yeah -- saw it later on that it was not a direct invocation of singularity (which also explained why image was not executable like it is when you get it with singularity pull).  But since git-annex can't/doesn't track any permissions (including executable bit) ATM there is little point in that aspect.

anyways -- I will look into adding progress reporting to add_url_to_file -- should be "easy" ;-)
