### ISSUE TITLE
Release please

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-container#57]
Enabled zenodo, we would get an entry with the new release. Currently at 0.2.1-15-g2b9462e

**Comment by bpoldrack** [comment]
Not sure, whether this was done at the time, but we urgently need a new release. Behavior is broken ATM. `containers-list` fails to discover recursively (and as a consequence `containers-run` fails) in the released version. Which is somewhat weird, since this should work before and after PR #65. There's something I don't quite get yet. As if that PR made it only half way in the current release. However, datalad-hirni usecase seems to work on master as well as it did before PR #65. But it doesn't with current release.

**Comment by kyleam** [comment]
> Not sure, whether this was done at the time,

@yarikoptic released 0.2.2 some time after that.

> but we urgently need a new release. Behavior is broken ATM. `containers-list` fails to discover recursively (and as a consequence `containers-run` fails) in the released version.

I'm not having luck triggering that.  My attempt is below.

> Which is somewhat weird, since this should work before and after PR #65. There's something I don't quite get yet. As if that PR made it only half way in the current release. However, datalad-hirni usecase seems to work on master as well as it did before PR #65. But it doesn't with current release.

I'm confused as well.  #65 was certainly merged (and branched off) after 7e1c9ce (Changes for 0.2.2 release, 2018-12-19).  It's not in any release.

---

```
% datalad subdatasets
subdataset(ok): subds (dataset)

# With 0.2.2 checked out.
% pip freeze | grep datalad
-e git+git@github.com:datalad/datalad.git@849eaed5f3a75631ab9a1df1ac1514be91004fe3#egg=datalad
-e git+git@github.com:datalad/datalad-container.git@7e1c9cefc4a5e736e2d8cf742062c0dd7e34c144#egg=datalad_container
% datalad containers-list  
containers(ok): /tmp/dc-YV8NAFV/subds/.datalad/environments/bb/image (file)
containers(ok): /tmp/dc-YV8NAFV/.datalad/environments/b/image (file)
action summary:
  containers (ok: 2)

# With master (which includes #65) checked out
% pip freeze | grep datalad
-e git+git@github.com:datalad/datalad.git@849eaed5f3a75631ab9a1df1ac1514be91004fe3#egg=datalad
-e git+git@github.com:datalad/datalad-container.git@876a982882ac78ed63639032ebea0f52c7d2cd6e#egg=datalad_container
% datalad containers-list  
containers(ok): /tmp/dc-YV8NAFV/.datalad/environments/b/image (file)
% datalad containers-list -r
containers(ok): /tmp/dc-YV8NAFV/subds/.datalad/environments/bb/image (file)
containers(ok): /tmp/dc-YV8NAFV/.datalad/environments/b/image (file)
action summary:
  containers (ok: 2)
```

**Comment by bpoldrack** [comment]
Hm. I had a venv with released version installed and got `containers-list` to report nothing at all (all containers in subdatasets) while not knowing an option `-r/--recursive`.

**Comment by kyleam** [comment]
Could that released version have been `<= 0.2.1`? That'd be before your 1e35339 (Recursively report registered containers from subdatasets, 2018-10-02).

**Comment by bpoldrack** [comment]
Currently I hesitate to rule anything (have an additional issue to solve with installing correct version of pytest, pytest-cov via pip), but that is *unlikely* since I build that venv from scratch just a week ago.

**Comment by bpoldrack** [comment]
However - don't spend time on this. There's something weird with my setup (in the context of datalad-hirni). Seems we agree on the need of a release - lets have that before digging into sth that may or may not be related. I really can't tell ATM.

**Comment by mih** [comment]
Waiting for https://github.com/datalad/datalad-container/pull/67 to get ready for a release.

**Comment by mih** [comment]
We have 0.3 out now.

**Comment by bpoldrack** [comment]
Sorry to bother you again, but due to the mess that was the difference between my local venvs and Travis' ones (not only datalad-container involved), I didn't mange to attribute that failure earlier. I'm afraid we need an instant release 0.3.1 with PR #68 merged.

**Comment by yarikoptic** [comment]
0.3.1 has happened, available from pypi, debian (experimental) and neurodebian -- thanks everyone ;-)
