### ISSUE TITLE
containers-* commands  takes awhile since interrogates full list of subdatasets

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-container#64]
Since https://github.com/datalad/datalad-container/pull/51 we by default list all containers even the ones discovered in subdatasets.  This takes awhile in sizeable datasets hierarchy.  I think we should just add `-r|--recursive` flag and interrogate subdatasets only if it is specified.  Would make behavior more consistent

**Comment by kyleam** [comment]
> I think we should just add `-r|--recursive` flag and interrogate subdatasets only if it is specified.

I agree that makes sense from both a performance and consistency perspective.

It looks like we'd have to update `containers-list` and `containers-run`.  I'm unsure about adding `--recursive` to `containers-run`, though.  I wonder if it'd be better to first see if the requested name is in `ContainersList.__call__(..., recursive=False)`, trying again with `ContainersList.__call__(..., recursive=True)` if it isn't.  (In the special case of an unspecified name, we'd need the two calls to make sure there is only a single container.)

Thoughts?

**Comment by yarikoptic** [comment]
run:  if that __call__ is a proper generator yielding first owned containers, then actually nothing to be done I guess if we decide to keep recursive lookup for run. 
I still wonder though if recursive lookup should happen by default - some paranoid fellas like yours truly might not even want to try to locate containers within 400 subdatasets some of which might come from outside. I also don't want to wait for a minute just to discover that I mistyped container name and none like that was (thank God) found among subdatasets. I think eventually we would want a config setting listing which subdatasets to explore for containers/procedures/etc. Alike mr does for repositories and chaining .mrconfig

**Comment by kyleam** [comment]
> run: if that `__call__` is a proper generator yielding first owned containers, then actually nothing to be done I guess if we decide to keep recursive lookup for run.

I haven't looked at this too deeply, but currently the top-level dataset's containers aren't yielded first:

```
$ datalad -f json_pp containers-list
{
  "action": "containers",
  "cmdexec": "singularity exec {img} {cmd}",
  "name": "subds/sky",
  "path": "/tmp/tmp.EbpGL1Un2I-dlc/subds/.datalad/environments/sky/image",
  "status": "ok",
  "type": "file",
  "updateurl": "shub://GodloveD/lolcow"
}
{
  "action": "containers",
  "cmdexec": "singularity exec {img} {cmd}",
  "name": "sky",
  "path": "/tmp/tmp.EbpGL1Un2I-dlc/.datalad/environments/sky/image",
  "status": "ok",
  "type": "file",
  "updateurl": "shub://GodloveD/busybox"
}
```

> I still wonder though if recursive lookup should happen by default - some paranoid fellas like yours truly might not even want to try to locate containers within 400 subdatasets some of which might come from outside. I also don't want to wait for a minute just to discover that I mistyped container name and none like that was (thank God) found among subdatasets.

Fair enough.  One more iteration on "run decides whether to pass recurse=True based on the name": names for subdataset containers have a "/", and that character isn't allowed in a top-level dataset name.  So what about doing recursive lookup only when the specified name contains "/"?  Recursion still could be triggered by mistyping, but it's less likely.

**Comment by bpoldrack** [comment]
> but currently the top-level dataset's containers aren't yielded first

Correct. It's bottom up, since this is the way the names are constructed.

> One more iteration on "run decides whether to pass recurse=True based on the name": names for subdataset containers have a "/", and that character isn't allowed in a top-level dataset name. So what about doing recursive lookup only when the specified name contains "/"?

Yes, that's what I thought as well. If we are going to do that, we could also consider to just "parse" the name and go down that path instead of triggering a "full" recursion. In that case `containers-run` would need to walk down via non-recursive `containers-list` calls.

However, I'd be not that quick about this:

> I think eventually we would want a config setting listing which subdatasets to explore for containers/procedures/etc. Alike mr does for repositories and chaining .mrconfig

Because the original idea was about toolbox datasets, that you can just install into your dataset and that would then provide containers/procedures. Such configs would make the installation of such toolboxes a lot more complicated. I do see how something like that can be useful (and even guard you), but this needs a second thought, I think.

**Comment by kyleam** [comment]
> If we are going to do that, we could also consider to just "parse" the name and go down that path instead of triggering a "full" recursion.

True.  And at that point we don't need to be too worried about unintentional execution since I think the problematic areas are restricted to things like "I wanted to execute 'my-thing' but I accidentally typed 'my/thing'".

**Comment by yarikoptic** [comment]
yep, sounds good (traversal via `/` present in the name)
