### ISSUE TITLE
singularity build fails to create correct image from docker://poldracklab/mriqc on smaug

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-container#70]
I did initially "containers-add", which completed Ok but image didn't "feel right". So did again - again the same. Did "manually":
```
$ singularity pull docker://poldracklab/mriqc
...
WARNING: Warning handling tar header: Can't create 'usr/local/miniconda/share/jupyter/kernels/python3/logo-64x64.png'
WARNING: Warning handling tar header: Can't create 'usr/local/miniconda/share/jupyter/nbextensions'
WARNING: Warning handling tar header: Can't create 'usr/local/miniconda/share/jupyter/nbextensions/jupyter-js-widgets'
WARNING: Warning handling tar header: Can't create 'usr/local/miniconda/share/jupyter/nbextensions/jupyter-js-widgets/extension.js'
WARNING: Warning handling tar header: Can't create 'usr/local/miniconda/share/jupyter/nbextensions/jupyter-js-widgets/extension.js.map'
WARNING: Warning handling tar header: Can't create 'usr/local/miniconda/share/man'
WARNING: Warning handling tar header: Can't create 'usr/local/miniconda/share/man/man1'
WARNING: Warning handling tar header: Can't create 'usr/local/miniconda/share/man/man1/ipython.1.gz'
WARNING: Warning handling tar header: Can't create 'usr/local/miniconda/xgboost'
WARNING: Warning handling tar header: Can't create 'usr/local/miniconda/xgboost/libxgboost.so'
WARNING: Warning handling tar header: Can't create 'usr/local/src/mriqc'
WARNING: Warning handling tar header: Can't create 'usr/local/src/mriqc/mriqc'
WARNING: Warning handling tar header: Can't create 'usr/local/src/mriqc/mriqc/VERSION'
Exploding layer: sha256:a4cca34e324bf4caf8ec6dce3881783e8fe1e3a6bb554234b1bd8a9110e064b7.tar.gz
Exploding layer: sha256:b21ed841574bd5ca0816169ed39d4fb446e37ee8446e7ab3a8d0802185a17df8.tar.gz
ERROR  : tar extraction error: Write failed
WARNING: Warning handling tar header: Write failed
ERROR  : tar extraction error: Write failed
WARNING: Warning handling tar header: Write failed
WARNING: Building container as an unprivileged user. If you run this container as root
WARNING: it may be missing some functionality.
Building Singularity image...
Singularity container built: ./mriqc.simg
Cleaning up...
Done. Container is at: ./mriqc.simg

$ echo $?
0
```
and there is now an image but it is incomplete.  Not sure yet what is the reason etc. Singularity is 2.6.1-2~nd90+1 .
But I wonder if we should parse output and warn if there was any WARNING from singularity

**Comment by bpoldrack** [comment]
Not sure whether it's worth parsing, but at least should let the output through, I guess.

**Comment by yarikoptic** [comment]
For passing (logging) output there is #69
Although relying on parsing is bad, I don't think we should log or pass output from a command which can produce lots of it

**Comment by yarikoptic** [comment]
I thought to suggest that we finally implement the fancy scrolling of output while retaining the errors/warnings, but looking now at the full output from `singularity` -- there were way too many errors and warnings ;)
With this command you could enjoy the "animation" how it could look while retaining errors/warnings:
```
$> wget -q -O- http://www.onerussian.com/tmp/mriqc.out | bash <(wget -q -O- https://raw.githubusercontent.com/yarikoptic/skroll/master/skroll) -m '\(WARNING\|ERROR\)'
```
So may be we should report a warning that there were warnings/errors and display the last (up to 10?) ones?

**Comment by bpoldrack** [comment]
Holy crap. ;-)

> So may be we should report a warning that there were warnings/errors and display the last (up to 10?) ones?

Might be the way to go. Apart from figuring out, what this actually is about and whether we can do something about it (I mean: The actual error).

**Comment by yarikoptic** [comment]
wow -- I suspect that the actual problem is "outdated" or broken tar on smaug/stretch (1.29b-1.1), where we get a warning first
```
WARNING: Warning reading tar header: Ignoring malformed pax extended attribute
```
singularity pulls fine on my laptop with tar 1.30+dfsg-3 . I am building a backport now to see if that would resolve it.

Actually it was somewhat eye opening to read recently https://www.cyphar.com/blog/post/20190121-ociv2-images-i-tar which nicely goes through the history of `tar` and outlines problems with it -- now I see it "in practice"

**Comment by yarikoptic** [comment]
ok - not tar itself, but likely the `libarchive13` (building backport of libarchive_3.3.3-4.dsc now) where this  warning originates (tar is not used directly, my bad ;-))

**Comment by yarikoptic** [comment]
ok, built/installed -- that WARNING is gone but following ones remained:
```
Exploding layer: sha256:b8ad75f9d9708fd1af5ff1b4a8ee544b4f2a09a21ea2229cf8f2c41e0becd400.tar.gz
ERROR  : tar extraction error: Write failed
WARNING: Warning handling tar header: Write failed
ERROR  : tar extraction error: Write failed
...
WARNING: Warning handling tar header: Failed to create dir 'usr/local/miniconda'
```
so there is more to it ... bleh

**Comment by yarikoptic** [comment]
oh damn -- that is probably the issue of `SINGULARITY_TMPDIR`... trying now

**Comment by yarikoptic** [comment]
yeap, that is it - 4GB was not enough under `/tmp` -- need to jungle partitions and increase size on smaug :-/
