### ISSUE TITLE
incorrect operation of containers-run from within subdirectories

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-container#72]
```shell
smaug:~/proj/nuisance$ cat .datalad/config
[datalad "dataset"]
        id = 1a495a66-b20d-11e8-9335-002590f97d84
[datalad "containers.reproin"]
        updateurl = shub://ReproNim/reproin:0.5.3
        image = .datalad/environments/reproin/image
        cmdexec = singularity exec {img} {cmd}
[datalad "containers.mriqc"]
        image = .datalad/environments/mriqc/image
        cmdexec = .datalad/environments/_bin/singularity-exec {img} {cmd}
[datalad "containers.simple-workflow"]
        image = .datalad/environments/simple-workflow/image
        cmdexec = singularity exec {img} {cmd}
```
and the shim is
```shell
smaug:~/proj/nuisance$ cat .datalad/environments/_bin/singularity-exec
#!/bin/bash

# A shim to take care about running sanitized home etc

bindir=$(dirname $0 | xargs readlink -f)
#echo "I: bindir=$bindir"
homedir=$(echo $bindir | xargs dirname )/_home
topdir=$(echo $bindir | xargs dirname | xargs dirname | xargs dirname )

echo "I: exec'ing with sanitized singularity with"
echo "I:   HOME=$homedir"
echo "I:   $topdir bind mounted"
singularity exec \
        -H "$homedir" \
        -B "$topdir:$topdir" \
        -e \
        "$@"
```

if I cd under `code/` subdirectory `containers-run` fails in a number of ways:
```shell
smaug:~/proj/nuisance/code$ datalad containers-run  -n mriqc --explicit pwd
[INFO   ] Making sure inputs are available (this may take some time) 
[WARNING] path not associated with any dataset [get(/home/chrispycheng/proj/.datalad/environments/mriqc/image)] 
[WARNING] Input does not exist: /home/chrispycheng/proj/.datalad/environments/mriqc/image 
[INFO   ] == Command start (output follows) ===== 
I: exec'ing with sanitized singularity with
I:   HOME=/home/chrispycheng/proj/nuisance/.datalad/environments/_home
I:   /home/chrispycheng/proj/nuisance bind mounted
ERROR  : Image path ../.datalad/environments/mriqc/image doesn't exist: No such file or directory
ABORT  : Retval = 255
[INFO   ] == Command exit (modification check follows) ===== 
CommandError: command '.datalad/environments/_bin/singularity-exec ../.datalad/environments/mriqc/image pwd' failed with exitcode 255
Failed to run '.datalad/environments/_bin/singularity-exec ../.datalad/environments/mriqc/image pwd' under '/home/chrispycheng/proj/nuisance'. Exit code=255.
```

for a shimmed one, and here is for the regular one:

```shell
smaug:~/proj/nuisance/code$ datalad containers-run  -n reproin --explicit pwd
[INFO   ] Making sure inputs are available (this may take some time) 
[WARNING] path not associated with any dataset [get(/home/chrispycheng/proj/.datalad/environments/reproin/image)] 
[WARNING] Input does not exist: /home/chrispycheng/proj/.datalad/environments/reproin/image 
[INFO   ] == Command start (output follows) ===== 
ERROR  : Image path ../.datalad/environments/reproin/image doesn't exist: No such file or directory
ABORT  : Retval = 255
[INFO   ] == Command exit (modification check follows) ===== 
CommandError: command 'singularity exec ../.datalad/environments/reproin/image pwd' failed with exitcode 255
Failed to run 'singularity exec ../.datalad/environments/reproin/image pwd' under '/home/chrispycheng/proj/nuisance'. Exit code=255
```

so it first seems to account for subdirectory while deducing (relative) image path, but then does `get` and the execution from the repo top directory, thus failing on both ends.

- FWIW `containers-list` seems to be ok
```shell
smaug:~/proj/nuisance/code$ datalad containers-list
containers(ok): /home/chrispycheng/proj/nuisance/.datalad/environments/mriqc/image (file)
containers(ok): /home/chrispycheng/proj/nuisance/.datalad/environments/reproin/image (file)
containers(ok): /home/chrispycheng/proj/nuisance/.datalad/environments/simple-workflow/image (file)
action summary:
  containers (ok: 3)
```

**Comment by kyleam** [comment]
Thanks for catching that.  I think the core issue is that we're explicitly passing dataset to run, so it operates on our "paths are relative to dataset" logic.  Taking a quit look, I think

```diff
diff --git a/datalad_container/containers_run.py b/datalad_container/containers_run.py
index 87d6270..a2b9c1d 100644
--- a/datalad_container/containers_run.py
+++ b/datalad_container/containers_run.py
@@ -95,7 +95,7 @@ def __call__(cmd, container_name=None, dataset=None,
         # fire!
         for r in Run.__call__(
                 cmd=cmd,
-                dataset=ds,
+                dataset=ds if ds.path == pwd else None,
                 inputs=inputs,
                 outputs=outputs,
                 message=message,
```

is our best option here.  I'll play around with that a bit more and make that into a proper PR (with a comment and a test).

**Comment by yarikoptic** [comment]
I expressed my fears for such a change in https://github.com/datalad/datalad/issues/3230#issue-421685792

**Comment by kyleam** [comment]
> I expressed my fears for such a change in [datalad/datalad#3230 (comment)](https://github.com/datalad/datalad/issues/3230#issue-421685792)

You said:
> since I am not sure what effect that would have, e.g. may be then making behavior different in the top directory of the dataset from how it would behave in subdirectory.

I can't really make sense of that.  The point *is* to make it behave differently, as it would beahve if we were not wrapping it and explicitly passing a dataset.  (This will be a general problem with wrapping datalad commands.) It's ugly because `containers-run` is using `run`s helper function to determine this information and then discarding it just so that `run` can do it all over again.  But without modifying a signature (of either `Run.__call__` or `run_command`) I don't see a way to convey this information.

**Comment by yarikoptic** [comment]
> I can't really make sense of that.

I am sorry

> The point is to make it behave differently, as it would beahve if we were not wrapping it and explicitly passing a dataset. ...

The only change I (as a user) expect is the difference in the run commit record, which would now should say that the command was ran within a subdirectory (`pwd` field) and the path to the image being adjusted in the `cmd` field to be relative to that subdirectory.  Other than that, behavior should stay the same - git submodules which were not a part of the dataset be consistently added or not, etc.

**Comment by kyleam** [comment]
> The only change I (as a user) expect is the difference in the run commit record, which would now should say that the command was ran within a subdirectory (`pwd` field) and the path to the image being adjusted in the `cmd` field to be relative to that subdirectory.

That is indeed the purpose of the proposed change.  (The proper PR will need a bit, but not much, more so that it works for python callers of `containers-run` too.)

AFAICT we're just talking past each other, so I'll drop this discussion until I actually create the PR.

**Comment by yarikoptic** [comment]
FWIW, @kyleam I have tested the proposed patch -- seems to work for me. So could it be finalized?

**Comment by kyleam** [comment]
> FWIW, @kyleam I have tested the proposed patch -- seems to work for me. So could it be finalized?

It is on my queue.  I'll get around to it.
