### ISSUE TITLE
More meaningful error message(s) whenever cmdexec contains "unknown" placeholders

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-container#75]
```shell
$> datalad containers-list
containers(ok): /home/yoh/proj/repronim/containers/singularity/bids/bids-validator--1.2.3 (file)

$> datalad containers-run 
[ERROR  ] u'dspath' [containers_run.py:__call__:87] (KeyError) 
```
since I thought (from `datalad run --help`) that `dspath` is available.  But I think it would be better to provide custom error message like

     `cmdexec` references an unknown placeholder `dspath`

or alike.
Also, it might be nice to verify (if possible) all those placeholders in `containers-add` whenever a custom `--call-fmt` was provided?

**Comment by kyleam** [comment]
@yarikoptic:

> $> datalad containers-run 
> [ERROR  ] u'dspath' [containers_run.py:__call__:87] (KeyError) 
> ```
> since I thought (from `datalad run --help`) that `dspath` is
> available.

The placeholders accepted by datalad-run are unrelated to the cmdexec
value stored in .datalad/config.  The placeholders in --call-fmt/cmdexec
are formatted by containers-run to generate the command it passes to
datalad-run.  As described by containers-add's help, the two
placeholders currently supported are "{img}" and "{cmd}".  If you want a
placeholder in cmdexec to make it through to datalad-run, you'd have to
put another layer of curly brackets around it.

> But I think it would be better to provide custom error message like
>
>      `cmdexec` references an unknown placeholder `dspath`
>
> or alike.

I agree that it'd be better for containers-run to catch the key error
and provide a more meaningful message (or ideally a result).
datalad-run already does so for its placeholders:

  $ datalad run "echo {dsspath}"
  run(impossible): /tmp/dlc-yk2LIS2 (dataset) [command has an unrecognized placeholder: 'dsspath']

I'll adjust containers-run to do similar.

> Also, it might be nice to verify (if possible) all those placeholders in `containers-add` whenever a custom `--call-fmt` was provided?

It is possible.  I wouldn't be opposed to a patch to do so, though I
personally think doing the check in containers-run is good enough and
maybe preferable so that the logic is in just one spot.
