### ISSUE TITLE
{pwd} placeholder for container's execmd

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-container#94]
there was #34 with closed-without-merge #35  which added `{pwd}` to be provided at `datalad run` level.  It is frequently (if not most of the time) needed to run within current directory within container. 
Singularity doesn't chdir to original pwd unless it is bound mounted.  Since by default it bind mounts HOME and /tmp/, in those directories things work as expected.  But if your current directory somewhere else -- you would need an explicit `--bind`.  With singularity 2.6.1-2~nd100+1 (on smaug):
```shell
$ cmd='singularity run /mnt/btrfs/datasets/datalad/crawl-misc/nwb/najafi-2018-nwb/environments/dandi-pynwb.simg bash -c "pwd"'

$ for d in ~/proj /tmp/subdir /data; do echo "D: $d"; ( builtin cd $d; eval $cmd; ); done
D: /home/yoh/proj
/home/yoh/proj
D: /tmp/subdir
/tmp/subdir
D: /data
/home/yoh
```
If PWD is bind mounted -- then things seems to work as expected. So default `cmdexec` for singularity containers is probably not usable when execution happens outside of HOME or /tmp. We would probably need to add an explicit --bind of PWD.  For that purpose we would need to expose `{pwd}` placeholder.  I also thought that it might be benefitial to be able to mount the entire dataset (when running within subdirectory), so ideally we add also `{dspath}` (which could differ from `{img_dspath}` e.g. when image is in a subdataset.

Related:
- #50 for sanitizing default execution
- a WiP (would still bug out due to IMHO a bug in singularity 3.x) "ultimate" shim which runs in sanitized environment and manually binds mounts all needed paths etc: https://github.com/ReproNim/containers/blob/master/scripts/singularity_cmd

**Comment by yarikoptic** [comment]
FTR -- singularity 3.1.1 seems to bind mount PWD (unless in `-c` mode) even when not under HOME or /tmp.

**Comment by yarikoptic** [comment]
ha -- the  workaround  was easy:
```
cmdexec = singularity exec --bind "$PWD" {img} {cmd}
```
since I guess we are invoking singularity in a shell.  But I still wonder what should we do if anything, i.e. just rely on having newer singularity for correct default operation?

**Comment by kyleam** [comment]
> FTR -- singularity 3.1.1 seems to bind mount PWD (unless in `-c` mode) even when not under HOME or /tmp.

I'm having a hard time keeping track of the singularity mounting issues across the different versions and flags :[    But FWIW on my end singularity version 2.6.1 seems to bind mount non-home/tmp PWDs when `-c` isn't given.

```
2.6.1-dist
+ pwd
+ singularity exec --bind /not-hometmp /tmp/bbox sh -c test -e /singularity && pwd
/not-hometmp
+ pwd
+ singularity exec --bind /not-hometmp -c /tmp/bbox sh -c test -e /singularity && pwd
/home/kyle
```

<details>
<summary>full script</summary>

```sh
#!/bin/sh

set -eu

singularity --version

if ! test -e /tmp/bbox
then
    (cd /tmp && singularity pull -n bbox docker://busybox:latest)
fi

testdir=${1:-/not-hometmp}
if test -e "$testdir"
then
    cd "$testdir"
else
    printf "test directory '%s' must already exist\n" "$testdir" >&2
    exit 1
fi

set -x
singularity exec --bind $(pwd)    /tmp/bbox sh -c "test -e /singularity && pwd"
singularity exec --bind $(pwd) -c /tmp/bbox sh -c "test -e /singularity && pwd"
```

</details>

**Comment by kyleam** [comment]
> ha -- the workaround was easy:
> 
> ```
> cmdexec = singularity exec --bind "$PWD" {img} {cmd}
> ```
> 
> since I guess we are invoking singularity in a shell. But I still wonder what should we do if anything, i.e. just rely on having newer singularity for correct default operation?

As I mentioned above, I'm not quite sure which singularity versions misbehave, but in general the downside of providing a full path `{pwd}` in cmdexec is that the resolved full path is stored in the run commit.

**Comment by yarikoptic** [comment]
> ```shell
> singularity exec --bind $(pwd) -c /tmp/bbox sh -c "test -e /singularity && pwd"
> ```

The initial report was about PWD not being mounted when no explicit `--bind $(pwd)` is provided.  If you do provide explicit `--bind` - it would get bind mounted.

> but in general the downside of providing a full path `{pwd}` in cmdexec is that the resolved full path is stored in the run commit.

good point.  So I could just rely on using env variable `$PWD` which shouldn't get expanded

**Comment by kyleam** [comment]
> The initial report was about PWD not being mounted when no explicit `--bind $(pwd)` is provided. If you do provide explicit `--bind` - it would get bind mounted.

Doh, got myself mixed up.  Sorry for the noise.

**Comment by yarikoptic** [comment]
I think this could be safely closed. verdict -- use `$PWD` where needed
