### ISSUE TITLE
{img_dspath} -- full or relative?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-container#95]
As a workaround for #94 I have tried to use `--bind {img_dspath}` .  Results surprised me twice:

1. `img_dspath` was provided a relative path (`.`) not absolute path
2. singularity (2.6.1-2~nd100+1) bugs out to take '.' as a relative path to some other than current directory:
```shell
$> pwd; singularity exec --bind . environments/dandi-pynwb.simg pwd
/mnt/btrfs/datasets/datalad/crawl-misc/nwb/najafi-2018-nwb

$> cat .datalad/config 
[datalad "dataset"]
        id = a0f8dc24-ad72-11e9-8c86-002590f97d84
[datalad "containers.dandi-pynwb"]
        updateurl = shub://dandi/najafi-2018-nwb
        image = environments/dandi-pynwb.simg
        cmdexec = singularity exec --bind {img_dspath} {img} {cmd}
```

I see the value in being able to refer to `img_dspath` as a relative path... may be I was the one who suggested that even?! ;)  but now I wonder what could/should we do to be able to specify singularity a proper full path?

FTR (edit 1):

<details>
<summary>singularity 3.1.1 seems to bind any PWD, and works out `--bind .`  correctly</summary> 

```shell
$> singularity exec -c --bind . /home/yoh/proj/dandi/nwb-datasets/najafi-2018-nwb/environments/dandi-pynwb.simg ls $PWD
abide  abide2  adhd200	corr  crcns  datapackage.json  dbic  devel  dicoms  hbnssi  indi  kaggle  labs	neurovault  nidm  openfmri  workshops
```
</details>

**Comment by kyleam** [comment]
> 2. singularity (2.6.1-2~nd100+1) bugs out to take '.' as a relative path to some other than current directory:

That's a bummer.

> I see the value in being able to refer to `img_dspath` as a relative path...

I do too.

> may be I was the one who suggested that even?! ;)

Almost certainly given that you were the one the added this feature in #76 :)

> but now I wonder what could/should we do to be able to specify singularity a proper full path?

To use the full path, could you do something like this?

    cmdexec = singularity exec --bind $PWD/{img_dspath} {img} {cmd}

I quickly tested outside of /home and /tmp and it seemed to work.

If the above works, I'd say that's probably good enough that given singularity v3 handles relative paths correctly.

**Comment by yarikoptic** [comment]
> If the above works, I'd say that's probably good enough that given singularity v3 handles relative paths correctly.

 yeap, will close
